import React from 'react';
import { useTheme } from '../context/ThemeContext';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsOfServiceScreen() {
  const { theme } = useTheme();

  return (
    <div className={`h-full flex flex-col ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
      <div className={`p-4 border-b flex items-center gap-4 ${theme === 'dark' ? 'border-gray-700 bg-gray-800' : 'border-gray-200 bg-white'}`}>
        <Link to="/settings" className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700">
          <ArrowLeft size={20} />
        </Link>
        <h1 className="text-lg font-semibold">Terms of Service</h1>
      </div>

      <div className="flex-1 overflow-y-auto p-6 max-w-3xl mx-auto">
        <div className={`prose ${theme === 'dark' ? 'prose-invert' : ''}`}>
          <h2>Terms of Service</h2>
          <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>

          <h3>1. Acceptance of Terms</h3>
          <p>
            By accessing or using Bible GPT, you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.
          </p>

          <h3>2. AI Content Disclaimer</h3>
          <p>
            Bible GPT utilizes artificial intelligence to generate responses. You acknowledge and agree that:
          </p>
          <ul>
            <li>AI responses are generated by algorithms and may contain errors or inaccuracies.</li>
            <li>The content provided is for spiritual and educational purposes and is not a substitute for professional theological, psychological, or medical advice.</li>
            <li>We are not responsible for any actions taken based on AI-generated content.</li>
          </ul>

          <h3>3. User Conduct and Reporting</h3>
          <p>
            You agree not to use the App to generate harmful, offensive, or inappropriate content. We provide a reporting mechanism (the "Flag" icon) for you to notify us of any inappropriate AI-generated content.
          </p>

          <h3>4. Disclaimer of Warranties</h3>
          <p>
            The App is provided "as is" without warranties of any kind. We do not guarantee the accuracy of the AI-generated responses.
          </p>

          <h3>5. Limitation of Liability</h3>
          <p>
            We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.
          </p>

          <h3>6. Changes to Terms</h3>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the App constitutes acceptance of the new terms.
          </p>
        </div>
      </div>
    </div>
  );
}
